
/**
 * Utility functions for generating and downloading signature analysis reports
 */

import { SignatureResultData } from '@/components/SignatureResult';

/**
 * Generates and downloads a simple text report for signature analysis results
 * 
 * Note: In a production app, this would generate a proper PDF or formatted document
 * using libraries like jsPDF, react-pdf, or send a request to a backend service
 */
export const downloadSignatureReport = (result: SignatureResultData) => {
  // Create report content
  const reportContent = generateReportContent(result);
  
  // Create a Blob from the report content
  const blob = new Blob([reportContent], { type: 'text/plain' });
  
  // Create a temporary URL to the blob
  const url = URL.createObjectURL(blob);
  
  // Create a link element to trigger the download
  const link = document.createElement('a');
  link.href = url;
  link.download = `signature-analysis-report-${new Date().getTime()}.txt`;
  
  // Append the link to the body
  document.body.appendChild(link);
  
  // Trigger the download
  link.click();
  
  // Clean up
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Generate the text content for the report
 */
const generateReportContent = (result: SignatureResultData): string => {
  const { isAuthentic, confidenceScore, matchDetails } = result;
  const scorePercent = Math.round(confidenceScore * 100);
  
  let content = `
SIGNATURE ANALYSIS REPORT
=========================
Generated: ${new Date().toLocaleString()}

RESULT: ${isAuthentic ? 'AUTHENTIC SIGNATURE' : 'POTENTIAL FORGERY'}
Confidence Score: ${scorePercent}%

`;

  if (matchDetails) {
    content += `
DETAILED ANALYSIS
----------------
Style Match: ${Math.round(matchDetails.styleMatch * 100)}%
Pressure Match: ${Math.round(matchDetails.pressureMatch * 100)}%
Flow Match: ${Math.round(matchDetails.flowMatch * 100)}%
`;
  }
  
  content += `
=========================
SignScan - Advanced Signature Verification
Generated by AI-powered signature analysis
`;

  return content;
};
